[env]
TERM = "xterm-256color"

[font]
size = 14

  [font.normal]
  family = "Iosevka Nerd Font"
  style = "Semi-Bold"

  [font.bold]
  family = "Iosevka Nerd Font"
  style = "Bold"

  [font.italic]
  family = "Iosevka Nerd Font"
  style = "Semi-Bold Italic"

  [font.bold_italic]
  family = "Iosevka Nerd Font"
  style = "Bold Italic"

[colors.primary]
background = "0x0d0d0d"
foreground = "0xb3b3b3"
## foreground = "0xa9b1d6" [Tokyonight default]

[colors.normal]
black = "0x32344a"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xad8ee6"
cyan = "0x449dab"
white = "0x787c99"

[colors.bright]
black = "0x444b6a"
red = "0xff7a93"

green = "0xb9f27c"
yellow = "0xff9e64"
blue = "0x7da6ff"
magenta = "0xbb9af7"
cyan = "0x0db9d7"
white = "0xacb0d0"

## BACKUP OLD COLORS
## [colors.primary]
## background = "0x070e12"
## foreground = "0xa9a9a9"
## 
## [colors.normal]
## black = "0x20201d"
## red = "0xd73737"
## green = "0x60ac39"
## yellow = "0xae9513"
## blue = "0x6684e1"
## magenta = "0xb854d4"
## cyan = "0x1fad83"
## white = "0xa9a9a9"
## 
## [colors.bright]
## black = "0x7d7a68"
## red = "0xd73737"
## green = "0x60ac39"
## yellow = "0xae9513"
## blue = "0x6684e1"
## magenta = "0xb854d4"
## cyan = "0x1fad83"
## white = "0xfefbec"

[colors.cursor]
text = "0x20201d"
cursor = "0xa9a9a9"
