# Enable mouse 
set -g mouse on

set-option -g status on
# set -g status-utf8 on # Does not work
set -g status-interval 5                  # set update frequency (default 15 secs)
set -g status-justify centre              # center window list for clarity
set-option -g status-position top         # position status bar at top of screen

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1

# visual notification of activity in other windows
setw -g monitor-activity on
set -g visual-activity on

# Enable vim bindings
set-window-option -g mode-keys vi
bind-key Escape copy-mode


# Colors...
set-option -g status-bg colour000
set-option -g status-fg colour45
set-option -g status-attr bright

set-window-option -g window-status-fg colour29 
set-window-option -g window-status-bg colour000

set-window-option -g window-status-current-fg colour45
set-window-option -g window-status-current-bg colour000     
# set-window-option -g window-status-current-attr dark

set-window-option -g window-status-current-format '[#I]#W  '
set-window-option -g window-status-format '[#I]#W  '

# set -g pane-active-border-style 

#set -g status-left "test"
set -g status-left "#{pane_current_path}"
set -g status-left-length 85

set -g status-right-length 60
#set -g status-right "test"
set -g status-right "#[fg=colour45]| Project: #S #[fg=colour45]| %d %b %Y #[fg= colour45]| %l:%M %p |"
#set -g status-left "#[fg=blue]#(tmux-cpu --no-color)"

#set -g pane-active-border-fg green
#set -g pane-border-fg black

bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

