format = """
$username\
$hostname\
$git_branch\
$directory\
"""
add_newline = false

[username]
style_user = 'white bold'
style_root = 'bold red'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)@[$hostname](bold red) '
disabled = false

[git_branch]
format = '\[[$branch(:$remote_branch)]($style)\] '
disabled = false


[directory]
read_only = ''
read_only_style = 'red'
